// <auto-generated />
using System;
using AFK.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AFK.Migrations
{
    [DbContext(typeof(AFKContext))]
    [Migration("20191203004754_AsignaturaMigracion")]
    partial class AsignaturaMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AFK.Models.Asignatura", b =>
                {
                    b.Property<int>("IDAsignatura")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreAsignatura");

                    b.HasKey("IDAsignatura");

                    b.ToTable("Asignatura");
                });

            modelBuilder.Entity("AFK.Models.Estudiante", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Edad");

                    b.Property<int?>("IDAsignatura");

                    b.Property<string>("Nombre");

                    b.Property<string>("Sexo");

                    b.HasKey("ID");

                    b.HasIndex("IDAsignatura");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("AFK.Models.Estudiante", b =>
                {
                    b.HasOne("AFK.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("IDAsignatura");
                });
#pragma warning restore 612, 618
        }
    }
}
